### ISSUE TITLE
pdd should store github user name not real name 

### ISSUE THREAD

**Issue by krzyk** [yegor256/pdd#105]
When 0pdd creates issues from puzzles it also mentions the puzzle created, e.g.: `The puzzle was created by Tolegen Izbassar on 22-May-18.`

This data is take from from XML produced by pdd, so pdd should store github username in xml, not users real name (which can be changed in github).

Instead of the real name of the author it would mention the github nick + make it a link to the user profile (not a mention).

It would make it more consistent with the rest of the repo comments.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#105](https://github.com/yegor256/pdd/issues/105) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/pdd/issues/105) assigned to @a6cexz[/z](https://www.0crat.com/u/a6cexz), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1870661965); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by a6cexz** [comment]
@yegor256 any idea how pdd can fetch github user name? currently it gets author using git blame, however, the name configured in git is not github user name.

**Comment by yegor256** [comment]
@a6cexz I have no idea right off the bat. @krzyk any ideas?

**Comment by krzyk** [comment]
@a6cexz @yegor256 OK, now I see the problem.

Is using github API an option?
I think we could https://developer.github.com/v3/search/#search-commits and select the commit that we have in the blame.
And from that response get `author.login` and `author.url`.

**Comment by a6cexz** [comment]
@krzyk thanks, this might do it, I think can simply query the search api to get login from email.
I think we can set github login in the author tag instead of git use name if github search query was successful

**Comment by a6cexz** [comment]
@krzyk the pull request #107 with fixes for this issue was recently merged, please close this job

**Comment by krzyk** [comment]
@a6cexz cool, thank you

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @a6cexz[/z](https://www.0crat.com/u/a6cexz)

**Comment by 0crat** [comment]
The job [#105](https://github.com/yegor256/pdd/issues/105) is now out of scope
