### ISSUE TITLE
Garbage characters in a puzzle name with HTML comment

### ISSUE THREAD

**Issue by php-coder** [yegor256/pdd#111]
For the following comment:

`<!-- @todo #493 AddCategoryDbDto: port to a new datetime API -->`

@0pdd created an issue with a title `AddCategoryDbDto: port to a new datetime API -->`

Expected result: puzzle shouldn't have `-->` at the end.

This issue is similar to #104 but with another comment type.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@php-coder[/z](https://www.0crat.com/u/php-coder) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@php-coder I don't think it's fixable... You formatted your puzzle incorrectly in the first place. It should be like this:

```
<!--
  @todo #493 AddCategoryDbDto: port to a new datetime API 
-->
```

**Comment by php-coder** [comment]
> I don't think it's fixable...

@yegor256 A similar comment was fixed in #104, so it's definitely fixable. So, now we have inconsistency when one type of comments works but another doesn't.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#111` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by php-coder** [comment]
> You formatted your puzzle incorrectly in the first place. It should be like this:

BTW it isn't documented anywhere and I haven't found examples of HTML comments in README. If it works not like a user expects then it should be documented at least.

**Comment by php-coder** [comment]
Faced this again... :(
