### ISSUE TITLE
Add a --pretend parameter

### ISSUE THREAD

**Issue by emilianodellacasa** [yegor256/pdd#112]
It happens often that the puzzle format it is not correct, but this is recognized only by travis, once that the code is sent to Github.

I think it will be useful to have a "--pretend" param, that performs the checks on the puzzle format and throws an error if something is wrong. 

This should be included for example in the "rake" task for Zold.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@emilianodellacasa[/z](https://www.0crat.com/u/emilianodellacasa) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@emilianodellacasa I'm not sure I understand. In order to check your source code just run:

```
$ pdd -f /dev/null
```

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#112` is not assigned, can't get performer
