### ISSUE TITLE
Rake task

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#114]
Let's create a rake task

You may see how Rake task is implemented in this repo: [yegor256/xcop](https://github.com/yegor256/xcop)

**Comment by aivinog1** [comment]
@yegor256 I want to help you with this one. I want to start with a small pull request with PDD todos.

**Comment by yegor256** [comment]
@aivinog1 great, let's do it. Here is where you can find a good example: https://github.com/yegor256/xcop/blob/master/lib/xcop/rake_task.rb Don't forget about unit tests.

**Comment by aivinog1** [comment]
@yegor256 Ok, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#114` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@yegor256 2 puzzles [#125](https://github.com/yegor256/pdd/issues/125), [#126](https://github.com/yegor256/pdd/issues/126) are still not solved.

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#126](https://github.com/yegor256/pdd/issues/126), [#132](https://github.com/yegor256/pdd/issues/132), [#133](https://github.com/yegor256/pdd/issues/133) are still not solved; solved: [#125](https://github.com/yegor256/pdd/issues/125).

**Comment by 0pdd** [comment]
@yegor256 3 puzzles [#132](https://github.com/yegor256/pdd/issues/132), [#133](https://github.com/yegor256/pdd/issues/133), [#135](https://github.com/yegor256/pdd/issues/135) are still not solved; solved: [#125](https://github.com/yegor256/pdd/issues/125), [#126](https://github.com/yegor256/pdd/issues/126).
