### ISSUE TITLE
Let's add support to JSON files

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/pdd#118]
Some configuration files have been written in JSON format. So let's add support to them. We can use something like: `"_comment": "@todo #123:30min Subject..."`. WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by lastk** [comment]
I don't think you should use a key in the json file to add a @todo. Depending of where/how you're using this file it may even trigger some error for having unsupported key. Maybe just add the puzzle where you're supposed to use the parsed config?

**Comment by fabriciofx** [comment]
@lastk you're right. I'll close this issue because it doesn't make any sense. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#118` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
