### ISSUE TITLE
Bin directory from rubocop is excluded

### ISSUE THREAD

**Issue by aivinog1** [yegor256/pdd#119]
See this: https://github.com/yegor256/pdd/blob/48cd3ba95a258e438ed9a0e5b0a37de71fdde57f/.rubocop.yml#L3

The bin folder must be checked by the Rubocop.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 feel free to submit a pull request

**Comment by yegor256** [comment]
@0crat assign @aivinog1

**Comment by 0crat** [comment]
> @0crat assign @aivinog1  ([here](https://github.com/yegor256/pdd/issues/119#issuecomment-509491531))

@yegor256 The job [#119](https://github.com/yegor256/pdd/issues/119) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/d18cb9fa-6142-47b0-ba32-3b22bbe2884d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @aivinog1[/z](https://www.0crat.com/u/aivinog1) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
@rultor[/z](https://www.0crat.com/u/rultor) the issue is closed not by @aivinog1[/z](https://www.0crat.com/u/aivinog1) (its creator); I won't close the order; please, re-open it and ask @aivinog1[/z](https://www.0crat.com/u/aivinog1) to close it

**Comment by aivinog1** [comment]
@yegor256 Can you reopen this ticket that I can close its properly.

**Comment by aivinog1** [comment]
@yegor256 ping.

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by aivinog1** [comment]
@0crat wait for reply from @yegor256

**Comment by 0crat** [comment]
> @0crat wait for reply from @yegor256 ([here](https://github.com/yegor256/pdd/issues/119#issuecomment-511218044))

@aivinog1 The impediment for [#119](https://github.com/yegor256/pdd/issues/119) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by yegor256** [comment]
@aivinog1 reopened

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by aivinog1** [comment]
@yegor256 Ok, I'm closing it.

**Comment by aivinog1** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/pdd/issues/119#issuecomment-511245869))

@aivinog1 This is what I know about this job in [C3T46CUJJ](https://www.0crat.com/p/C3T46CUJJ), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#119](https://github.com/yegor256/pdd/issues/119) is [in scope](http://www.zerocracy.com/policy.html#14) for 6days
  * The role is `DEV`
  * The job is assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1) for [6days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C3T46CUJJ?q=%7Bjob%3A%27gh%3Ayegor256%2Fpdd%23119%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
Job [#119](https://github.com/yegor256/pdd/issues/119) is not in the agenda of @aivinog1[/z](https://www.0crat.com/u/aivinog1), can't inspect

**Comment by 0crat** [comment]
@dennis00010011b[/z](https://www.0crat.com/u/dennis00010011b) please review this job completed by @aivinog1[/z](https://www.0crat.com/u/aivinog1), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#119](https://github.com/yegor256/pdd/issues/119) is now out of scope
