### ISSUE TITLE
Build of the project is broken.

### ISSUE THREAD

**Issue by aivinog1** [yegor256/pdd#121]
Found in #120. 

For now, a build of the whole project is broken (see this: https://travis-ci.org/yegor256/pdd/builds/556113316?utm_source=github_status&utm_medium=notification).

I suppose that we need to update the ruby version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by aivinog1** [comment]
@yegor256 if don't mind I'll try to fix this issue myself.

**Comment by aivinog1** [comment]
@yegor256 I see that since f14af438f5e24f01754d654018740e79f3ee1efd the project doesn't have  success build at all.

**Comment by 0crat** [comment]
Job [#121](https://github.com/yegor256/pdd/issues/121) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#121` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#121](https://github.com/yegor256/pdd/issues/121) is now out of scope
