### ISSUE TITLE
Needs to fix collecting puzzles in the project

### ISSUE THREAD

**Issue by aivinog1** [yegor256/pdd#124]
For now, puzzles are failed to collect, see this: https://github.com/yegor256/pdd/pull/122#commitcomment-34229389. 

It needs to investigate and make puzzles collectible.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 fixed in 5a9c16f thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#124` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
