### ISSUE TITLE
Pdd can't create a github label

### ISSUE THREAD

**Issue by aivinog1** [yegor256/pdd#128]
See this: https://github.com/yegor256/pdd/issues/126#issuecomment-509496510

The message of the issue is pretty clear: 

> I can't create GitHub labels pdd. Most likely I don't have necessary permissions to yegor256/pdd repository. 

Needs to fix it.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@aivinog1[/z](https://www.0crat.com/u/aivinog1) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@aivinog1 fixed already, thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#128` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
