### ISSUE TITLE
rake.feature:9-10: For now, there is a warning when I run...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/pdd#135]
The puzzle `126-b07582a4` from #126 has to be resolved: 

https://github.com/yegor256/pdd/blob/7f32468a6720c188f0364f6285cc5a98c490f387/features/rake.feature#L9-L10

The puzzle was created by Alexey Vinogradov on 11-Jul-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@0crat assign @aivinog1

**Comment by 0crat** [comment]
> @0crat assign @aivinog1  ([here](https://github.com/yegor256/pdd/issues/135#issuecomment-511229203))

@yegor256 The job [#135](https://github.com/yegor256/pdd/issues/135) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/f458e24c-15a9-4baa-a715-10cf66609e9c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @aivinog1[/z](https://www.0crat.com/u/aivinog1) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by aivinog1** [comment]
@0crat wait #136

**Comment by 0crat** [comment]
> @0crat wait #136 ([here](https://github.com/yegor256/pdd/issues/135#issuecomment-511334596))

@aivinog1 The impediment for [#135](https://github.com/yegor256/pdd/issues/135) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0pdd** [comment]
The puzzle `126-b07582a4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#135](https://github.com/yegor256/pdd/issues/135) is not in the agenda of @aivinog1[/z](https://www.0crat.com/u/aivinog1), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#135](https://github.com/yegor256/pdd/issues/135) is not in the agenda of @aivinog1[/z](https://www.0crat.com/u/aivinog1), can't inspect

**Comment by 0crat** [comment]
@dennis00010011b[/z](https://www.0crat.com/u/dennis00010011b) please review this job completed by @aivinog1[/z](https://www.0crat.com/u/aivinog1), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#135](https://github.com/yegor256/pdd/issues/135) is now out of scope
