### ISSUE TITLE
0pdd bot does not respond on PR merge in devsuperstars/m16

### ISSUE THREAD

**Issue by agorlov** [yegor256/pdd#137]
Pre:
repo ``devsuperstars/m16``
**0pdd** is collaborator, and webhook added.
I create pull request, then merge it.

Problem:
0pdd bot does not respond on PR merge. (without error message)

My gues - this is due to the size of the repository. (Its old and large project ~450Mb)
Anyway, my expectation, to get explicit message from bot.

![image](https://user-images.githubusercontent.com/2485728/62789420-8bece480-bad1-11e9-9410-39457fe1c966.png)

![image](https://user-images.githubusercontent.com/2485728/62789579-e423e680-bad1-11e9-9c0f-c817997ebe44.png)

Tried several times.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@agorlov[/z](https://www.0crat.com/u/agorlov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@agorlov what kind of response you expect from it? If there are no puzzles in your code, it won't say anything.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#137` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
