### ISSUE TITLE
pdd is very slow

### ISSUE THREAD

**Issue by ribtoks** [yegor256/pdd#139]
I'm trying to run pdd on the repository https://github.com/ribtoks/xpiks using command `pdd -s ./src` and it is too slow on my macbook pro.

Even though it does not finish scan (it exited on some non-excluded binary `.rc` file), it took time measured with ~a watch~ `time` utility

    real	1m22.272s
    user	0m41.352s
    sys	0m28.555s

With this limitation, it is not viable to use this tool for real workflow locally.

Although it sounds sarcastic, in reality it might be easier and faster to replace the pdd with a `perl` script. Or rewrite using approaches in https://github.com/junegunn/fzf tool - it is capable of finding regexes way faster than `pdd` while being truly cross-platform and dependency-free (`pdd` requires ruby runtime and 5 gems).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ribtoks[/z](https://www.0crat.com/u/ribtoks) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by ribtoks** [comment]
I wrote a [tool](https://github.com/ribtoks/tdg) in Go in a couple of hours that does the same as pdd and finished execution in less than 1 second (on my machine) on the same codebase. You can close the issue if you think 1.5 minutes execution time is OK for your tool.

**Comment by yegor256** [comment]
@ribtoks but this tool not only scans files but also validates what it finds, performs a number of checks, and creates a multi-level XML document. I'm sure it's possible to make it faster, but it's not a simple scanner. Anyway, I like the tool you created!

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#139` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
