### ISSUE TITLE
Add optional parameter to specify milestone an issue should be linked to

### ISSUE THREAD

**Issue by ChameleonTartu** [yegor256/pdd#140]
We miss the functionality of linking `todo` to `milestone`.

Use case. I have planned release and tasks with No milestones. I want to be able to add tasks to the same current milestone or another milestone. It will help to either postpone deadlines when scope cannot be reduced or pass tasks to the future milestone.

Example of syntax can be:

```
/**
 * @todo #[issue#]/<#[milestone#]><:[time]></[role]> <[description]>
 */
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@chameleontartu[/z](https://www.0crat.com/u/chameleontartu) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@ChameleonTartu PDD is not for planning, it's for finding puzzles and reporting them. The planning should happen afterwards, in the issue tracker, by hands. The author of the puzzle must not make these decisions.
