### ISSUE TITLE
How to add a code snippets into @todo?

### ISSUE THREAD

**Issue by dgroup** [yegor256/pdd#142]
Let's say we have a code
```java
...
/**
 * Javadoc.
 * @todo #/DEV In order to ... we may need to use
 *   new Assertion(
 *      "scenario",
 *       actualObject
 *       expectedMatcher
 *   ).affirm()
 *   Ensure that ...
 */
public void method() {
...
```

In this case, `pdd` will throw the exception with a clarification that 'Too many leading spaces'.
Is there any option to hint pdd about code snippets?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dgroup the only option I have is this:

```
/**
 * Javadoc.
 * @todo #/DEV In order to ... we may need to use
 *  . new Assertion(
 *  .    "scenario",
 *  .     actualObject
 *  .     expectedMatcher
 *  . ).affirm()
 *  . Ensure that ...
 */
```

**Comment by dgroup** [comment]
I see, this is a workaround, but it works)

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#142` is not assigned, can't get performer
