### ISSUE TITLE
Supported tickets management systems are not listed in the README.md

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/pdd#144]
I would like to use the system with JIRA, but I cannot figure out if JIRA is supported by this product. The README.md file only partially mentions Github.

It's a bug, that there is no explicit list of supported ticket management systems somewhere on the main page (most likely - README.md).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yuri-karpovich** [comment]
Great project! I like a concept and want to contribute. We need to create an interface to connect issues management systems like JIRA or Redmine

**Comment by yegor256** [comment]
@proshin-roman this product is not connected to any ticket tracking system. It just parses the source code and creates an XML file with a full list of _puzzles_. If you need integration with your tracker, you should check 0pdd.com at https://github.com/yegor256/0pdd

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#144` is not assigned, can't get performer
