### ISSUE TITLE
Supported services of VCS are not listed in the README.md

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/pdd#145]
I would like to use the product with Bitbucket (uses Git), but cannot figure out from the product documentation whether Bitbucket is supported, or it's only about Github (which de-facto default).

It's a bug, that there is no explicit list of supported VCS services supported by the product. Such a list must be somewhere in the documentation, most likely in README.md.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@proshin-roman you should check https://github.com/yegor256/0pdd This repo is not doing anything with GitHub or JIRA. See also #144

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#145` is not assigned, can't get performer
