### ISSUE TITLE
Make puzzle discovery more resilient?

### ISSUE THREAD

**Issue by amihaiemil** [yegor256/pdd#146]
Would it be possible to make the puzzle discovery a little more robust? For instance, it will fail for the following puzzle:

```java
/**
 * @todo: #427:30min Implement and test method Task::Task.unassign().
 *  This method should remove the assignee and leave the Task unassigned.
 */
public class SomeClass {
...
}
```
just because there is an unwanted ``:`` right after the ``@todo``.

I think if the parent ticket and estimation cannot be parsed for some reason (while the overall todo is parseable), then it should return the puzzle with ``unknown`` or ``undefined`` values for what it couldn't parse.

**Comment by yegor256** [comment]
@amihaiemil well, we are big fans of strict rules, as you know :) Let's keep our code clean and consistent.

**Comment by amihaiemil** [comment]
@yegor256 we decided to write our own parser in the meantime, with blackjack and hookers B-)

**Comment by yegor256** [comment]
@amihaiemil great!)

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#146` is not assigned, can't get performer
