### ISSUE TITLE
Is it possible to change how much have spaces after the next line?

### ISSUE THREAD

**Issue by portlek** [yegor256/pdd#149]
https://github.com/yegor256/pdd/blob/master/lib/pdd/source.rb#L145
Because my Javadoc style is like that;
![image](https://user-images.githubusercontent.com/12835420/103161473-28ad4080-47f3-11eb-93b7-c9ec188cf0d7.png)
So, I want to make the spaces 2.

**Comment by yegor256** [comment]
@portlek it's not configurable at the moment. You are welcome to submit a pull request with this configuration option though.

**Comment by portlek** [comment]
> @portlek it's not configurable at the moment. You are welcome to submit a pull request with this configuration option though.

thanks, if I can learn to ruby I'll make it ASAP .-.

**Comment by mbao01** [comment]
Fixed in PR #160
