### ISSUE TITLE
Pdd doesnt recognize multilines puzzle description.

### ISSUE THREAD

**Issue by dzhukovski** [yegor256/pdd#150]
Pdd was not able to recognize such description. (all tabs and spaces are make the difference). When I put this description into single line everything been parsed properly.

```
        /**
         * @todo #2:30m/DEV Create Test project solution architecture.
         * Add IEntity type
         * Add ICar type
         * Add IPayment type
         * Add IRent type
         */

```

**Comment by mbao01** [comment]
Hi @dzhukovski thanks for submitting this issue. I looked through and noticed the todo marker you have is not properly formatted. Check the readme on [how to format](https://github.com/yegor256/pdd#how-to-format)

**Right**
```
/**
 * @todo #2:30m/DEV Create Test project solution architecture.
 *  Add IEntity type
 *  Add ICar type
 *  Add IPayment type
 *  Add IRent type
 */
```

**Wrong**
```
/**
 * @todo #2:30m/DEV Create Test project solution architecture.
 * Add IEntity type
 * Add ICar type
 * Add IPayment type
 * Add IRent type
 */
```

**Comment by dzhukovski** [comment]
Hi @mbao01 , thanks for the clarification, but to be honest its pretty weird that the format I used can not be considered as a proper one. Anyway thanks a lot.

**Comment by yegor256** [comment]
@dzhukovski this is my design. The only space for us to understand where you puzzle ends is by the indentation.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#150` is not assigned, can't get performer
