### ISSUE TITLE
--exclude doesn't glob correctly

### ISSUE THREAD

**Issue by alxn** [yegor256/pdd#32]
Help says this:

``` shell
$ pdd --help | grep exc
    -e, --exclude      Glob pattern to exclude
```

Yet:

``` shell
$ pdd --file=/dev/null --exclude target/*
INFO: "my version is 0.14"
INFO: "reading ."
INFO: "excluding target/archive-tmp"
<snip>
INFO: "puzzle 95:30/IMP at target/it/mapping-mode/src/test/java/com/xockets/layer/mapping/MappingModeTest.java"
```

``` shell
$ pdd --file=/dev/null --exclude "target/*"
INFO: "my version is 0.14"
INFO: "reading ."
INFO: "excluding target/*"
<snip>
INFO: "puzzle 95:30/IMP at target/it/mapping-mode/src/test/java/com/xockets/layer/mapping/MappingModeTest.java"
```

**Comment by yegor256** [comment]
try this:

```
pdd --file=/dev/null --exclude "target/**"
```

**Comment by alxn** [comment]
negative Houston:

```shell
$ pdd --file=/dev/null --exclude "target/**"
INFO: "my version is 0.14"
INFO: "reading ."
INFO: "excluding target/**"
<snip>
INFO: "puzzle 95:30/IMP at target/it/mapping-mode/src/test/java/com/xockets/layer/mapping/MappingModeTest.java"
```

There is a workaround of:
```shell
$ pdd --file=/dev/null --source src/
```

**Comment by yegor256** [comment]
@alxn can't be negative! look at this line: https://github.com/teamed/pdd/blob/master/.rultor.yml#L21 This is how it works here, in this project

**Comment by alxn** [comment]
That seems to be a shell glob:
```shell
$ echo test/** features/** README.md
test/test_duplicates.rb test/test_estimates.rb test/test__helper.rb test/test_pdd.rb test/test_roles.rb test/test_source.rb test/test_sources.rb test/test_text.rb features/applies_rules.feature features/avoiding_duplicates.feature features/catches_broken_puzzles.feature features/cli.feature features/gem_package.feature features/html_output.feature features/parsing.feature features/step_definitions features/support features/unicode.feature features/uses_config.feature README.md
```
Note it doesn't find: 
```shell
$ echo features/*/*
features/step_definitions/steps.rb features/support/env.rb
```
Should [`pdd/sources.rb`](https://github.com/teamed/pdd/blob/master/lib/pdd/sources.rb#L42) use a [`Dir.glob()`](http://ruby-doc.org/core-2.2.0/Dir.html#method-c-glob) ?

**Comment by yegor256** [comment]
@alxn `Dir.glob()` doesn't understand exclusions. That's why we're using this code. But it works, right?

**Comment by yegor256** [comment]
@alxn is there still an issue here?

**Comment by alxn** [comment]
@yegor256 I thought so I did pull the code, but need to repro it locally. Will try in a bit.

**Comment by alxn** [comment]
So I created some files with puzzles:
```shell
alun@alun-evanss-mbpr-pdd-> find testing -type f
testing/file
testing/more/file
alun@alun-evanss-mbpr-pdd-> cat testing/file
/*
 * @todo #234:15m/DEV This is something else to do later
 */

alun@alun-evanss-mbpr-pdd-> cat testing/more/file
/*
 * @todo #234:15m/DEV This is something to do later
 */
```
And `pdd` can find them:
```shell
bin/pdd --source=$(pwd) --verbose --file=pdd.xml -e=test/** -e=features/** -e=README.md
INFO: "my version is 0.14"
INFO: "reading /Users/alun/Xockets/Code/teamed/pdd"
INFO: "excluding test/*"
INFO: "excluding features/*"
INFO: "excluding README.md"
INFO: "32 file(s) found"
fatal: no such path 'testing/file' in HEAD
INFO: "puzzle 234:15/DEV at testing/file"
fatal: no such path 'testing/more/file' in HEAD
INFO: "puzzle 234:15/DEV at testing/more/file"
```
but if I try to `-e=testing/**` it only drops the top level, not the hierarchy:
```shell
alun@alun-evanss-mbpr-pdd-> bin/pdd --source=$(pwd) --verbose --file=pdd.xml -e=test/** -e=features/** -e=README.md -e=testing/**
INFO: "my version is 0.14"
INFO: "reading /Users/alun/Xockets/Code/teamed/pdd"
INFO: "excluding test/**"
INFO: "excluding features/**"
INFO: "excluding README.md"
INFO: "excluding testing/**"
INFO: "30 file(s) found"
fatal: no such path 'testing/more/file' in HEAD
INFO: "puzzle 234:15/DEV at testing/more/file"
```

**Comment by alxn** [comment]
@yegor256 - was tempted, with the following, but can't yet workout how to use a local lib:

```diff
diff --git a/lib/pdd.rb b/lib/pdd.rb
index f550cf4..347a2ff 100644
--- a/lib/pdd.rb
+++ b/lib/pdd.rb
@@ -84,8 +84,10 @@ module PDD
       PDD.log.info "reading #{dir}"
       sources = Sources.new(dir)
       @opts[:exclude].each do |p|
-        sources = sources.exclude(p)
         PDD.log.info "excluding #{p}"
+        Dir.glob(p) do |g|
+          sources = sources.exclude(g)
+          PDD.log.info "excluding #{g}"
       end unless @opts[:exclude].nil?
       sanitize(
         rules(
```

**Comment by 0crat** [comment]
Job [#32](https://github.com/yegor256/pdd/issues/32) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#32](https://github.com/yegor256/pdd/issues/32) is already in scope

**Comment by 0crat** [comment]
The job [#32](https://github.com/yegor256/pdd/issues/32) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1451505158); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)com.zerocracy.Par@128c5d66

**Comment by 0crat** [comment]
The user @pbenety[/z](https://www.0crat.com/u/pbenety) resigned from [#32](https://github.com/yegor256/pdd/issues/32), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by pbenety** [comment]
@alxn I did some tests and to exclude recursively you need to use `**/*`

```
$ pdd --verbose --file=/dev/null -e=test/**
Reading C:/Users/Benety/development/projects/testing
Excluding test/**
4 file(s) found, 5 excluded
Reading src/file1.txt...
Reading src/file2.txt...
Reading src/subdir/file3.txt...
Reading test/subdir/test3.txt...
```

Using `**\*` pdd gets all files.
```
$ pdd --verbose --file=/dev/null -e=test/**/*
Reading C:/Users/Benety/development/projects/testing
Excluding test/**/*
3 file(s) found, 6 excluded
Reading src/file1.txt...
Reading src/file2.txt...
Reading src/subdir/file3.txt...
```

**Comment by 0crat** [comment]
The job [#32](https://github.com/yegor256/pdd/issues/32) assigned to @vl3[/z](https://www.0crat.com/u/vl3), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1551528998); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vl3** [comment]
@yegor256 
@alxn 

What would be the workaround this? 
As @pbenety said:
`$ pdd --verbose --file=/dev/null -e=dir_to_exclude/**/*`
works fine.

Should `$ pdd --verbose --file=/dev/null -e=dir_to_exclude/*` exclude all files inside _dir_to_exclude_ or it's just fine the way it is now?

**Comment by 0crat** [comment]
@vl3[/z](https://www.0crat.com/u/vl3) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by vl3** [comment]
I know that the bug is old but i'm doing my best to close it. 
I think that it is invalid, it works as expected using _-e dir_to_exclude/**/*_. Globstar (**) is a feature that was introduced in bash 4 and in most shells  ** is equally expanded as *, as you can see:
```
% echo *                                                                                                                                                                                     
dir_to_exclude dir_to_include ile
% echo **                                                                                                                                                                                    
dir_to_exclude dir_to_include ile
```
@yegor256 Could you clarify what would be the expected behaviour of this? I think that the way it is it is just fine.

**Comment by yegor256** [comment]
@vl3 let's just close it, thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @vl3[/z](https://www.0crat.com/u/vl3)

**Comment by 0crat** [comment]
The job [#32](https://github.com/yegor256/pdd/issues/32) is now out of scope
