### ISSUE TITLE
Detect malformed puzzles

### ISSUE THREAD

**Issue by pinaf** [yegor256/pdd#34]
If a puzzle is created without the `#` character in front of the issue, pdd should detect it and complain.

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@pinaf thanks for the ticket, your account was topped for 15 mins, payment AP-2BH61194JP656145Y

**Comment by yegor256** [comment]
@pinaf I believe it's fixed, check the latest version please. If you see this or similar problems again, please don't hesitate to open a new ticket.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/pdd#34`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#34` is not in scope.
