### ISSUE TITLE
Puzzle never extracted silently

### ISSUE THREAD

**Issue by longtimeago** [yegor256/pdd#48]
Puzzle below will never be extracted **silently**.

``` java
    @Override
    //@todo #945:30min Lets remove logging once #945 is resolved.
    // This logging was added to investigate original issue and should be
    // removed once #945 is resolved. Do not forget to remove helper methods
    // also.
    public XsLayer.Job job(final int job) { }
```

because twin slash is not followed by whitespace at the first line

Let's either fix the pattern to parse such puzzle or reject this format at all.

**Comment by davvd** [comment]
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@longtimeago I believe it's fixed already. If you see this problem again, please report.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#48` is not assigned, can't get start time

**Comment by longtimeago** [comment]
@yegor256 sure :D

**Comment by 0crat** [comment]
Job [#48](https://github.com/yegor256/pdd/issues/48) was not in scope
