### ISSUE TITLE
Describe local installation of PDD to Windows/MacOS

### ISSUE THREAD

**Issue by alexey-krylov** [yegor256/pdd#49]
Current installation manual covers only debian-based linux distributives (apt-get install).
It will be nice to have Windows + MacOS installation manual.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@alexey-krylov take a look: 1137402 works?

**Comment by yegor256** [comment]
@alexey-krylov I'm not sure this will work on RedHat... can you please confirm?

**Comment by yegor256** [comment]
@alexey-krylov I believe it's easy now, we don't have any specific dependencies anymore.
