### ISSUE TITLE
upgrade slop to 4.0

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#51]

**Comment by davvd** [comment]
@yegor256 I just added bug tag here

**Comment by davvd** [comment]
@yegor256 thanks for reporting! I topped your account for 15 mins, transaction 000-fc7c31ba

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor deploy

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#51` was not in scope
