### ISSUE TITLE
pdd should fail build if @todo is not following a whitespace

### ISSUE THREAD

**Issue by krzyk** [yegor256/pdd#53]
pdd should fail a build if `@todo` is after a non-whitespace character.

E.g. Incorrect puzzle:

```
        <!--@todo #909:30min jcabi-parent used by Netbout is pretty outdated,   
              we should update it to the latest version and make sure the build 
              is passing                                                        
        -->                                                                     
```

`@todo` should either start before any characters in a line or should be after a whitespace.

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.2`

**Comment by yegor256** [comment]
@rultor release, tag is `0.18.3`

**Comment by yegor256** [comment]
@krzyk I believe it's fixed, try version 0.18.3. If you have any similar issues, please submit a new ticket. I'm closing this one.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/pdd#53`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#53` is not in scope.
