### ISSUE TITLE
README.md:42-44: This is something to do later in one of ...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/pdd#59]
The puzzle `234-b843faac` in `README.md` (lines 42-44) has to be resolved: This is something to do later in one of the next releases. I can't figure out how how to implement it now, that's why the puzzle.

The [puzzle](http://www.yegor256.com/2009/03/04/pdd.html) was created by Yegor Bugayenko on 23-Jan-17. 

Estimate: 15 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is removed from the source code.

**Comment by 0pdd** [comment]
@yegor256 please pay attention to this new issue.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `234-b843faac` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#59` is not in scope

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
