### ISSUE TITLE
Puzzle in xml parsed partial..

### ISSUE THREAD

**Issue by DronMDF** [yegor256/pdd#65]
puzzle in xml parse only first line of multiline puzzle.

[This is a text](https://github.com/DronMDF/laweb/blob/master/lawe/templates/operations.xml#L12-L15)

[This is a issue](https://github.com/DronMDF/laweb/issues/59)

I can not understand how to make the right format in xml...
The truth is this is not really xml...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF this is how it should be:

```
<!-- 
@todo #55:30min Необходимо добавить сюда признак доступности счета
 Чтобы можно было отфильтровать доступные счета для формы
 И при этом использовать данные отсюда в таблице ниже
 (а не хранить имена и там) 
-->
```

**Comment by DronMDF** [comment]
Where is it described in the documentation?
I tried to find them in the source code, but I could not.

pdd understand puzzle changes?

**Comment by DronMDF** [comment]
Not understand. Pdd close one issue and open other.
Ok, problem is solved.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#65` was not in scope
