### ISSUE TITLE
exceptions are not verbose enough

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#67]
We must give a link to the formatting rules

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.8`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#67` was not in scope
