### ISSUE TITLE
pull request notifications

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#68]
Every time we see a new pull request we must calculate what it gives us, in terms of adding new puzzles and removing existing now. And then post a message to the pull request with a quick summary of what's going to happen. Just like codecov.io is doing about code coverage, for example: https://github.com/yegor256/cactoos/pull/48

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#68` was not in scope

**Comment by yegor256** [comment]
migrated to https://github.com/yegor256/0pdd/issues/124
