### ISSUE TITLE
Pdd closing active puzzle issues..

### ISSUE THREAD

**Issue by DronMDF** [yegor256/pdd#70]
dronmdf/2out#58 is closed, but puzzle text still in source code. 

https://github.com/DronMDF/2out/blob/master/src/TextReport.cpp#L31

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF can you please re-submit it here: https://github.com/yegor256/0pdd/issues

**Comment by DronMDF** [comment]
Sorry.
