### ISSUE TITLE
max-duplicates not work

### ISSUE THREAD

**Issue by Slach** [yegor256/pdd#71]
i run following command
```
gem install pdd
pdd --source=./src/ --verbose --file=pdd.xml --exclude=github.com/**/* --rule=available-roles:DEV,PM,ARCH,QA --rule=min-words:4 --rule=max-duplicates:10 
```

but catch following error
```
ERROR: "there are 3 duplicate(s) of the same puzzle: unoKvClient/api.go:118-118, unoKvClient/api.go:141-141, unoKvClient/api.go:148-148, while maximum 1 duplicate is allowed"
D:/Portable/ruby/lib/ruby/gems/2.3.0/gems/pdd-0.17.8/lib/pdd.rb:150:in `rules': 1 errors, see log above (PDD::Error)
        from D:/Portable/ruby/lib/ruby/gems/2.3.0/gems/pdd-0.17.8/lib/pdd.rb:92:in `xml'
        from D:/Portable/ruby/lib/ruby/gems/2.3.0/gems/pdd-0.17.8/bin/pdd:63:in `<top (required)>'
        from D:/Portable/ruby/bin/pdd:22:in `load'
        from D:/Portable/ruby/bin/pdd:22:in `<main>'
```

could you explain me how to use max-duplicates rule correctly ?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Slach this is because of this line: https://github.com/yegor256/pdd/blob/0.17.8/lib/pdd.rb#L141 Let me try to fix it.

**Comment by yegor256** [comment]
@rultor release, tag is `0.17.9`

**Comment by yegor256** [comment]
@Slach try it now. The problem is that we can't allow multiple duplicates in our XML report. They will cause many troubles in the future. So, `max-duplicates:1` is the best we can afford.

**Comment by Slach** [comment]
ok. can you remove max-duplicates from README ?

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#71` was not in scope
