### ISSUE TITLE
pdd is not process changes

### ISSUE THREAD

**Issue by DronMDF** [yegor256/pdd#74]
PR https://github.com/DronMDF/goost/pull/177 contain 2 new puzzle, and 1 removed puzzle.
PR merged in master.
Current (removed) puzzle still open.
New puzzle not created...

Service was down?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by DronMDF** [comment]
Sorry, i'm wrong.
Last version pdd parsed sources without problem.
This is a service problem.
https://github.com/yegor256/0pdd/issues/110

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#74` was not in scope
