### ISSUE TITLE
PDD should fail if "todo" is invalid

### ISSUE THREAD

**Issue by g4s8** [yegor256/pdd#77]
I mistyped `todo` comment with witespace after `#` char :
```
@todo # 266:30min some-text...
```
PDD just skipped this comment without error.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#77` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4320](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#77` is already assigned to @yegor256.

**Comment by 0crat** [comment]
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment]
@yegor256 resigned from `gh:yegor256/pdd#77`, please stop working.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#77` is not assigned to anyone.

**Comment by yegor256** [comment]
@g4s8 seems to be a duplicate of #34

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @tedtoer, total is [+120](http://www.0crat.com/u/tedtoer).

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#77` is now out of scope.
