### ISSUE TITLE
Add more details about puzzle format

### ISSUE THREAD

**Issue by php-coder** [yegor256/pdd#79]
I'm trying to use pdd and it fails:
> ERROR: /home/coder/mystamps/src/main/java/ru/mystamps/web/controller/SeriesController.java; @todo found, but puzzle can't be parsed in line #236, most probably because TODO is not followed by a puzzle marker, as this page explains: https://github.com/yegor256/pdd#how-to-format

Here is my TODO:
```java
// @todo SeriesController: extract method that will add common attributes to the model
List<CategoryDto> categories = categoryService.findCategoriesWithParents(lang);
```

The things that I'd like to see clarified:
- does it support any form of the comments? (`//`, `#`, etc) or only `/** */`?
- is it required that a comment should be on a method? Could I put it on a class or any other line of code?
- is it required to write a comment in javadoc style? Does it support `/* */`?
- is it required to have a puzzle marker? May I only provide a text?
- how this markers related to the issue labels?
- is it possible to configure pdd in a such way, so all the issues that it creates, will have "techdebt" label?

Thanks!

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by php-coder** [comment]
> is it possible to configure pdd in a such way, so all the issues that it creates, will have "techdebt" label?

Self-answer: https://github.com/yegor256/0pdd/issues/27

**Comment by php-coder** [comment]
> is it required to have a puzzle marker? May I only provide a text?

I've created https://github.com/yegor256/pdd/issues/81 for that.

**Comment by yegor256** [comment]
@php-coder see 97306c3 Is it better now?

**Comment by php-coder** [comment]
Yes, it's much better now! Thanks!

Could you also mention about subject/body format? You could enhance the existing example (with `sendEmail()` method) by writing something like that:
"After processing this method, the issue titled "File.java:10-10: This is something to do later..." will be created. The specified markers will be included in the issues body along with a some predefined text. If your comment is longer than 60 characters, then it will appear truncated in the title."

**Comment by yegor256** [comment]
@php-coder how about now? 0f3ed2f

**Comment by php-coder** [comment]
@yegor256 I posted my comment there.

**Comment by yegor256** [comment]
@php-coder see c635735

**Comment by php-coder** [comment]
Thanks!

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/pdd#79`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#79` is not in scope.
