### ISSUE TITLE
exit code doesn't work

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#83]

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.19.2`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/pdd#83`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#83` is not in scope.
