### ISSUE TITLE
broken emails should not break XML

### ISSUE THREAD

**Issue by yegor256** [yegor256/pdd#85]
For some reason we sometimes may have something instead of valid emails in Git logs. Let's filter them out so that they don't break the XML.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#85` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#85` assigned to @tedtoer. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
@tedtoer this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@tedtoer resigned from `gh:yegor256/pdd#85`, please stop working.

**Comment by 0crat** [comment]
Job [#85](https://github.com/yegor256/pdd/issues/85) is already in scope

**Comment by 0crat** [comment]
The job [#85](https://github.com/yegor256/pdd/issues/85) assigned to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/451433435). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rok-povsic** [comment]
@yegor256 Can you please give an example of a log where this occurs?

**Comment by yegor256** [comment]
@rok-povsic try this, in an empty local Git repo:

```
$ git config user.email 'hello, world!'
$ touch x
$ git add x
$ git commit -am 'test'
[master (root-commit) b07c472] test
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 x
$ git log
commit b07c472f26940675d7b073f79e2222dcb5a20a06 (HEAD -> master)
Author: Yegor Bugayenko <hello, world!>
Date:   Thu Feb 15 01:26:32 2018 +0300

    test
```

See the problem?

**Comment by rok-povsic** [comment]
Hi @yegor256 , please close this issue, thanks.

**Comment by rok-povsic** [comment]
@yegor256 Ping.

**Comment by yegor256** [comment]
@rok-povsic thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.1`

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @rok-povsic[/z](https://www.0crat.com/u/rok-povsic), total is [+120](https://www.0crat.com/u/rok-povsic)

**Comment by 0crat** [comment]
The job [#85](https://github.com/yegor256/pdd/issues/85) is now out of scope
