### ISSUE TITLE
Document the process of file renaming

### ISSUE THREAD

**Issue by php-coder** [yegor256/pdd#87]
I've just tried and see that if you rename a file with a comment but don't modify a comment itself, it doesn't affect existing issues! I was afraid that the old one will be closed and another one created as the file name has been changed.

I think it's good to explicitly states that in the documentation.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@php-coder check 1d6c76c what do you think?

**Comment by php-coder** [comment]
Thanks! It's better now. It's a bit deep in the paragraph, but at least it exits.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#87` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/pdd#87` was not in scope
