### ISSUE TITLE
PDD can't parse another project markers

### ISSUE THREAD

**Issue by g4s8** [yegor256/pdd#89]
I'm trying to add a puzzle with a marker's link to another Github project:
```java
/**
 * @todo zerocracy/datum#179 ...some text...
 */
```
but `pdd` tool show an error:
> ERROR: puzzle at line #35; @todo found, but puzzle can't be parsed, most probably because @todo is not followed by a puzzle marker, as this page explains

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@g4s8 cross-projects markers are not supported, and should not be. PDD is only about one single repository, always.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#89` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#89](https://github.com/yegor256/pdd/issues/89) was not in scope
