### ISSUE TITLE
0pdd is not parse puzzle on debian/stretch?!?

### ISSUE THREAD

**Issue by DronMDF** [yegor256/pdd#90]
Build failed on circleci
https://circleci.com/gh/DronMDF/2out/62?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

pdd-0.20: Successfully installed pdd-0.20

```
ERROR: .travis.yml; puzzle at line #53; @todo found, but puzzle can't be parsed, most probably because @todo is not followed by a puzzle marker...
```

Puzzle:
https://github.com/DronMDF/2out/blob/issue-288/.travis.yml#L53-L55

Puzzle is ok, on Travis pdd-0.20 pass without errors
https://travis-ci.org/DronMDF/2out/jobs/336446384

About system:
circleci: debian/stretch
travis: ubuntu/trusty

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@DronMDF I can't find where PDD works inside Travis... The puzzle obviously has an error. It spells:

```
@todo: #251
```

But it should be:

```
@todo #251
```

**Comment by DronMDF** [comment]
Oh, yes... this is intresting..
On travis pdd invoke from style.sh... It is not invoked?
Upgrade local pdd to 0.20 and problem reproduced locally.
Thanks.

**Comment by 0crat** [comment]
Job `gh:yegor256/pdd#90` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#90](https://github.com/yegor256/pdd/issues/90) was not in scope
