### ISSUE TITLE
RuboCop does not pass on AppVeyor

### ISSUE THREAD

**Issue by rok-povsic** [yegor256/pdd#92]
For example see [this build](https://ci.appveyor.com/project/yegor256/pdd-k8m39/build/70). 

RuboCop passes on Travis for the same build.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@rok-povsic should be fine now, after b650b69

**Comment by yegor256** [comment]
@rok-povsic all good: https://ci.appveyor.com/project/yegor256/pdd-k8m39
