### ISSUE TITLE
Pdd ignore invalid markers

### ISSUE THREAD

**Issue by g4s8** [yegor256/pdd#94]
It seems that #77 and #34 bugs are reproducing again. `pdd` just skip invalid marker `@todo # 496:30min` here: https://github.com/zerocracy/farm/pull/705/files#diff-2a22f8d917b8e9354b8bad65c444fd5e without errors. I think it should fail in such case.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#94](https://github.com/yegor256/pdd/issues/94) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/641352255). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job [#94](https://github.com/yegor256/pdd/issues/94) is already in scope

**Comment by yegor256** [comment]
@g4s8 it's fixed, thanks!

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#94](https://github.com/yegor256/pdd/issues/94) is now out of scope
