### ISSUE TITLE
Single leading space

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/pdd#97]
> puzzle at line #37; Space expected at 38:3

But 38:3 is space.
Here: https://github.com/yegor256/cactoos-http/pull/17#issuecomment-383935296

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@vssekorin[/z](https://www.0crat.com/u/vssekorin) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3T46CUJJ) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
