### ISSUE TITLE
Many tests are ignored or broken

### ISSUE THREAD

**Issue by SilasReinagel** [yegor256/pdd#98]
I was trying to begin development on Pdd features, and the tests are in a very bad state of disrepair. Many are ignored or fail:

`test_pdd.rb`
Failed - test_basic
Not Detected - test_rules_failure
Ignored (Windows) - test_git_repo

`test_sources.rb`
Failed - test_fails_with_verbose_output
Ignored (Windows) - test_ignores_binary_files
Not Detected - test_detects_all_text_files
Not Detected - test_detects_xml_file
Not Detected - test_excludes_by_pattern

`test_source.rb`
Ignored - test_parsing
Ignored - test_failing_on_invalid_puzzle
Not Detected - test_failing_on_incomplete_puzzle 
Ignored (Windows) - test_failing_on_broken_unicode
Ignored - test_failing_on_invalid_puzzle_without_hash_sign
Not Detected - test_failing_on_puzzle_without_leading_space
Not Detected - test_failing_on_puzzle_with_space_after_dash
Ignored (Windows) - test_reads_git_author
Ignored (Windows) - test_skips_invalid_git_mail

These tests should be fixed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#98](https://github.com/yegor256/pdd/issues/98) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @silasreinagel[/z](https://www.0crat.com/u/silasreinagel)

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/pdd/issues/98) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C3T46CUJJ/1551541463); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting for review #101

**Comment by 0crat** [comment]
> @0crat waiting for review #101 ([here](https://github.com/yegor256/pdd/issues/98#issuecomment-396779370))

@pbenety The impediment for [#98](https://github.com/yegor256/pdd/issues/98) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0pdd** [comment]
@SilasReinagel the puzzle [#102](https://github.com/yegor256/pdd/issues/102) is still not solved.

**Comment by pbenety** [comment]
@SilasReinagel please close this issue. The PR #101 that fix some tests was merged and the puzzle #102 was added to fix the ignored tests in Windows.

**Comment by SilasReinagel** [comment]
@pbenety Tests are still broken on Windows. You'll need to open at leas tone more ticket, or fixed the offending non-ignored test.

```
# Running:

..The system cannot find the path specified.
The system cannot find the path specified.
....S...S.S...F

Failure:
TestSources#test_fails_with_verbose_output [D:/srcctrl/pdd-master/test/test_sources.rb:98]:
84ls2/z1.txt; puzzle at line #1; @todo found, but puzzle can't be parsed, most probably because @todo is not followed by a puzzle marker, as this page explains: https://github.com/yegor256/pdd#how-to-format


bin/rails test D:/srcctrl/pdd-master/test/test_sources.rb:92

..The system cannot find the path specified.
ERROR: Puzzle jx2n6/a.txt:1-1 has an estimate of 0 minutes, which is lower than 30 minutes
.SThe system cannot find the path specified.
E

Error:
TestPDD#test_basic:
RuntimeError: doesn't match '/puzzles/puzzle[file="a.txt"]': <?xml version="1.0"?>
<?xml-stylesheet type='text/xsl' href='http://pdd-xsl.teamed.io/1.0.snapshot.xsl'?>
<puzzles xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://pdd-xsd.teamed.io/1.0.snapshot.xsd" version="1.0.snapshot" date="2018-06-30T17:00:06Z">
  <puzzle>
    <ticket>55</ticket>
    <estimate>0</estimate>
    <role>DEV</role>
    <id>55-5a8dd3ad</id>
    <lines>1-1</lines>
    <body>hello!</body>
    <file>lyx3j/a.txt</file>
  </puzzle>
</puzzles>

    D:/srcctrl/pdd-master/test/test_pdd.rb:106:in `block in matches'
    D:/srcctrl/pdd-master/test/test_pdd.rb:105:in `each'
    D:/srcctrl/pdd-master/test/test_pdd.rb:105:in `matches'
    D:/srcctrl/pdd-master/test/test_pdd.rb:36:in `block in test_basic'
    D:/Languages/Ruby/Ruby23-x64/lib/ruby/2.3.0/tmpdir.rb:89:in `mktmpdir'
    D:/srcctrl/pdd-master/test/test_pdd.rb:33:in `test_basic'


bin/rails test D:/srcctrl/pdd-master/test/test_pdd.rb:32

.....

Finished in 0.295418s, 91.3960 runs/s, 115.0913 assertions/s.
27 runs, 34 assertions, 1 failures, 1 errors, 4 skips

You have skipped tests. Run with --verbose for details.
```

**Comment by SilasReinagel** [comment]
@pbenety Okay. There is still something broken. I can open a new bug later. At least this is some progress on making the build work.

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
The job [#98](https://github.com/yegor256/pdd/issues/98) is now out of scope
